### ISSUE TITLE
id and url need corrected

### ISSUE THREAD

**Issue by chrisroederucdenver** [timsbiomed/owl-on-fhir-content#1]
For files that load into hapi there are both id and url fields.

  "id": "hpo",
  "url": "http://purl.obolibrary.org/obo/hp.fhir",

I'm just seeing an id with a url for these files, and HAPI complains.

The put request repeats the id in the URL/query-string. I haven't tried combinations that either leave out the URL or properly escape a URL passed as an id.

**Comment by joeflack4** [comment]
Fixed in latest release
