### ISSUE TITLE
Release file naming

### ISSUE THREAD

**Issue by ShahimEssaid** [timsbiomed/owl-on-fhir-content#6]
The release file names should have the pattern  "ResourceType-id.json"  and the "id" portion has to be an exact string match to the value in the "id" filed in the JSON object.  "ResourceType" is CodeSystem, ValueSet, etc.

Also, the "id" value has to pass: http://hl7.org/fhir/datatypes.html#id

CodeSystem-CompLOINC.json in the 1-9 release does not follow this pattern.

**Comment by ShahimEssaid** [comment]
@joeflack4 I still see an issue with file names vs resource id.  

For example: CodeSystem-so.json   has resource id "CodeSystem-so".  The resource id in this case should be "so".

I will fix manually this time to try to load the content.

**Comment by joeflack4** [comment]
Wow, I'm surprised I misread this. the OP looks different than what I remember; I though this was what you asked. I must have just been rushing. Go ahead and fix manually but I will fix this in the next release.

**Comment by joeflack4** [comment]
Fixed in the last release
